// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvTXxYUMUcrF8uAQ_KgPX_Hf_YCaCT52Y',
    appId: '1:405130473643:web:d44eba099555d19cdac7ee',
    messagingSenderId: '405130473643',
    projectId: 'compare-app-f00bb',
    authDomain: 'compare-app-f00bb.firebaseapp.com',
    storageBucket: 'compare-app-f00bb.appspot.com',
    measurementId: 'G-EGDJP1JJWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZXUuTq_Mm0EIAOdvMQYgWs4IlQVoUNTQ',
    appId: '1:405130473643:android:5750991010684decdac7ee',
    messagingSenderId: '405130473643',
    projectId: 'compare-app-f00bb',
    storageBucket: 'compare-app-f00bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2U-D3LXFY618v_Vzeo_qw_4OhTIcnGv8',
    appId: '1:405130473643:ios:c4dd4c51a8875cdfdac7ee',
    messagingSenderId: '405130473643',
    projectId: 'compare-app-f00bb',
    storageBucket: 'compare-app-f00bb.appspot.com',
    iosBundleId: 'com.example.compareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2U-D3LXFY618v_Vzeo_qw_4OhTIcnGv8',
    appId: '1:405130473643:ios:c4dd4c51a8875cdfdac7ee',
    messagingSenderId: '405130473643',
    projectId: 'compare-app-f00bb',
    storageBucket: 'compare-app-f00bb.appspot.com',
    iosBundleId: 'com.example.compareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvTXxYUMUcrF8uAQ_KgPX_Hf_YCaCT52Y',
    appId: '1:405130473643:web:303f407b6310613fdac7ee',
    messagingSenderId: '405130473643',
    projectId: 'compare-app-f00bb',
    authDomain: 'compare-app-f00bb.firebaseapp.com',
    storageBucket: 'compare-app-f00bb.appspot.com',
    measurementId: 'G-RGNNHE9PK8',
  );
}
